config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  devise_for :users, controllers: { registrations: 'registrations' }

  namespace :admin do
    resources :goals
    resources :categories
    resources :users
    resources :ledgers

    get 'home/index'

    # Charts JSON APIs
    get 'charts/:type/goal/:id/logs(/date/:start_date)', to: 'charts#goal_logs', as: 'charts_goal_logs'
  end

  authenticated :user do
    root to: 'admin/home#index', as: :authenticated_root
  end

  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= Rails.application.config.application_name %> | Admin</title>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <%= csrf_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= favicon_link_tag asset_path('favicon.ico'), :rel => 'icon', :type => "image/x-icon" %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag 'admin/layout/fontastic', media: 'all', 'data-turbolinks-track': 'reload' %>
  <!-- jQuery Circle-->
  <%= stylesheet_link_tag 'admin/layout/grasp_mobile_progress_circle-1.0.0.min', media: 'all', 'data-turbolinks-track': 'reload' %>
  <!-- Custom Scrollbar-->
  <%= stylesheet_link_tag 'admin/layout/jquery.mCustomScrollbar', media: 'all', 'data-turbolinks-track': 'reload' %>
  <!-- theme stylesheet-->
  <%= stylesheet_link_tag 'admin/layout/style.default', media: 'all', 'data-turbolinks-track': 'reload' %>
  <!-- Custom stylesheet - for our changes-->
  <%= stylesheet_link_tag 'admin/layout/custom', media: 'all', 'data-turbolinks-track': 'reload' %>
  <!-- Google fonts - Roboto -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700">


  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>

<!-- Side Navbar -->
<nav class="side-navbar">
  <div class="side-navbar-wrapper">
    <!-- Sidebar Header    -->
    <div class="sidenav-header d-flex align-items-center justify-content-center">
      <!-- User Info-->
      <div class="sidenav-header-inner text-center">
        <%= fa_icon ['user-circle', '4x'] %>
        <h2 class="h5">
          <%= link_to current_user.full_name, edit_user_registration_path %>
        </h2>
        <span>&nbsp;</span>
      </div>
      <!-- Small Brand information, appears on minimized sidebar-->
      <div class="sidenav-header-logo">
        <a href="index.html" class="brand-small text-center"> <strong>B</strong><strong class="text-primary">D</strong></a>
      </div>
    </div>
    <!-- Sidebar Navigation Menus-->
    <div class="main-menu">
      <h5 class="sidenav-heading">Main</h5>
      <ul id="side-main-menu" class="side-menu list-unstyled">
        <li class="<%= active_controller?('admin/home') %>">
          <%= link_to(admin_home_index_path) do %>
            <%= fa_icon 'home' %>Home
          <% end %>
        </li>
        <li class="<%= active_controller?('admin/goals') %>">
          <%= link_to(admin_goals_path) do %>
            <%= fa_icon 'bullseye' %>Goals
          <% end %>
        </li>
        <li class="<%= active_controller?('admin/categories') %>">
          <%= link_to(admin_categories_path) do %>
            <%= fa_icon 'list' %>Categories
          <% end %>
        </li>
      </ul>
    </div>
    <% if current_user.admin? %>
      <div class="admin-menu">
        <h5 class="sidenav-heading">Site Admin</h5>
        <ul id="side-admin-menu" class="side-menu list-unstyled">
          <li>
            <a href="#">
              <%= link_to(admin_users_path) do %>
                <%= fa_icon 'users' %>Users
              <% end %>
            </a>
          </li>
        </ul>
      </div>
    <% end %>
  </div>
</nav>
<div class="page">
  <!-- navbar-->
  <header class="header">
    <nav class="navbar">
      <div class="container-fluid">
        <div class="navbar-holder d-flex align-items-center justify-content-between">
          <div class="navbar-header">
            <a id="toggle-btn" href="#" class="menu-btn"><i class="icon-bars"> </i></a><a href="index.html" class="navbar-brand">
            <div class="brand-text d-none d-md-inline-block">
              <span><%= Rails.application.config.application_name %> </span><strong class="text-primary">Dashboard</strong>
            </div>
          </a></div>
          <ul class="nav-menu list-unstyled d-flex flex-md-row align-items-md-center">
            <li class="nav-item">
              <%= link_to(destroy_user_session_path, class: 'nav-link logout', id: 'logout') do %>
                Logout<i class="fa fa-sign-out"></i>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </header>

  <main>

    <section class="main-section">
      <% if flash[:notice] %>
        <div class="alert alert-success"><%= flash[:notice] %></div>
      <% end %>
      <% if flash[:alert] %>
        <div class="alert alert-danger"><%= flash[:alert] %></div>
      <% end %>

      <%= yield %>
    </section>
  </main>

  <footer class="main-footer">
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-6">
          <p>Bijan Hoomand &copy; 2018</p>
        </div>
        <div class="col-sm-6 text-right">
          <p>Template Designed by <a href="https://bootstrapious.com" class="external">Bootstrapious</a></p>
        </div>
      </div>
    </div>
  </footer>
</div>

<!-- Javascript files-->
<%= javascript_include_tag 'admin/layout/grasp_mobile_progress_circle-1.0.0.min', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'admin/layout/jquery.cookie', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'admin/layout/jquery.validate.min', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'admin/layout/jquery.mCustomScrollbar.concat.min', 'data-turbolinks-track': 'reload' %>
<!-- Main File-->
<%= javascript_include_tag 'admin/layout/front', 'data-turbolinks-track': 'reload' %>
</body>
</html>