config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  devise_for :users, controllers: { registrations: 'registrations' }

  namespace :admin do
    resources :goals
    resources :categories
    resources :users
    resources :ledgers

    get 'home/index'

    # Charts JSON APIs
    get 'charts/:type/goal/:id/logs(/date/:start_date)', to: 'charts#goal_logs', as: 'charts_goal_logs'
  end

  authenticated :user do
    root to: 'admin/home#index', as: :authenticated_root
  end

  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :goals, dependent: :destroy
  enum unit_type: {
    boolean: 0,
    number: 1,
    percent: 2
  }

  validates :name, presence: true
  validates :unit_type, presence: true
end

app/controllers/admin/categories_controller.rb
module Admin
  class CategoriesController < Admin::ApplicationController
    before_action :authenticate_user!

    def new
      @category = Category.new
    end

    def create
      @category = Category.new(category_params)
      @category.user = current_user
      if @category.save
        flash[:notice] = 'Category created successfully'
        redirect_to admin_categories_path
      else
        flash[:alert] = 'Invalid category'
        render 'new'
      end
    end

    def index
      @categories = current_user.categories
    end

    def show; end

    def edit
      @category = find_or_redirect(:category, params[:id])
    end

    def update
      @category = find_or_redirect(:category, params[:id])
      return if @category.nil?
      @category.update(category_params)

      flash[:notice] = 'Category updated'
      redirect_to admin_categories_path
    end

    def destroy
      @category = find_or_redirect(:category, params[:id])

      @category.destroy
      flash[:notice] = "Category #{@category.name} was deleted successfully"
      redirect_to admin_categories_path
    end

    private

    def category_params
      params.require(:category).permit(:name, :unit_type, :unit_name)
    end
  end
end

app/views/admin/categories/_form.html.erb
<div class="card-body">
  <%= form_for [:admin, category], html: {class: 'form-horizontal'} do |f| %>
    <% if category.errors.any? %>
      <% category.errors.full_messages.each do |msg| %>
        <div class="alert alert-danger"><%= msg %></div>
      <% end %>
    <% end %>

    <div class="form-group row">
      <%= f.label :name, class: 'col-sm-3 form-control-label' %>
      <div class="col-sm-9">
        <%= f.text_field :name, class: 'form-control', placeholder: 'book, video training, kindle book' %>
      </div>
    </div>
    <div class="line"></div>
    <div class="form-group row">
      <%= f.label :unit_type, 'Unit Type', class: 'col-sm-3 form-control-label' %>
      <div class="col-sm-3">
        <%= f.radio_button :unit_type, 'number' %>
        <%= f.label "unit_type_number", 'Number' %>
      </div>
      <div class="col-sm-3">
        <%= f.radio_button :unit_type, 'percent' %>
        <%= f.label "unit_type_percent", 'Percent' %>
      </div>
      <div class="col-sm-3">
        <%= f.radio_button :unit_type, 'boolean' %>
        <%= f.label "unit_type_boolean", 'True/False' %>
      </div>
    </div>
    <div class="line"></div>
    <div class="form-group row">
      <%= f.label :unit_name, 'Unit Name', class: 'col-sm-3 form-control-label' %>
      <div class="col-sm-9">
        <%= f.text_field :unit_name, class: 'form-control', placeholder: 'pages (i.e. for a book category), clips (i.e. for a video training category)' %>
      </div>
    </div>

    <div class="form-group row">
      <div class="col-sm-3">&nbsp;</div>
      <div class="col-sm-4">
        <%= link_to 'Cancel', admin_categories_path, class: 'btn btn-secondary' %>
        <%= f.submit "Submit", class: 'btn btn-primary' %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/categories/delete.html.erb
<h1>Admin::Categories#delete</h1>
<p>Find me in app/views/admin/categories/delete.html.erb</p>

app/views/admin/categories/edit.html.erb
<div class="card-header d-flex align-items-center">
  <h3 class="h4">Edit Category</h3>
</div>
<%= render 'form', category: @category %>

app/views/admin/categories/index.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center">
    <h3 class="h4">Categories</h3>
  </div>
  <div class="card-body">
    <div class="table-responsive table-striped">
      <table class="table">
        <thead>
        <tr>
          <th>Name</th>
          <th>Unit Type</th>
          <th>Unit Name</th>
          <th>Creation Date</th>
          <th>Last Update</th>
          <th>&nbsp;</th>
          <th>&nbsp;</th>
        </tr>
        </thead>
        <tbody>
        <% @categories.each do |category| %>
          <tr>
            <td><%= category.name %></td>
            <td><%= category.unit_type %></td>
            <td><%= category.unit_name %></td>
            <td><%= category.created_at_formatted %></td>
            <td><%= category.updated_at_formatted %></td>
            <td>
              <%= link_to(edit_admin_category_path(category), id: "edit_category_#{category.id}") do %>
                <%= fa_icon 'edit' %>

              <% end %>
            </td>
            <td>
              <%= link_to(
                      admin_category_path(category),
                      method: :delete,
                      data: { confirm: 'Are you sure?' },
                      authenticity_token: true,
                      class: 'danger',
                      id: "delete_category_#{category.id}") do %>
                <%= fa_icon 'trash' %>

              <% end %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <%= link_to 'Add', new_admin_category_path, class: 'btn btn-primary' %>
  </div>
</div>

app/views/admin/categories/new.html.erb
<div class="card-header d-flex align-items-center">
  <h3 class="h4">Add Category</h3>
</div>
<%= render 'form', category: @category %>

app/views/admin/categories/show.html.erb
<h1>Admin::Categories#show</h1>
<p>Find me in app/views/admin/categories/show.html.erb</p>

app/views/admin/categories/update.html.erb
<h1>Admin::Categories#update</h1>
<p>Find me in app/views/admin/categories/update.html.erb</p>