config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  devise_for :users, controllers: { registrations: 'registrations' }

  namespace :admin do
    resources :goals
    resources :categories
    resources :users
    resources :ledgers

    get 'home/index'

    # Charts JSON APIs
    get 'charts/:type/goal/:id/logs(/date/:start_date)', to: 'charts#goal_logs', as: 'charts_goal_logs'
  end

  authenticated :user do
    root to: 'admin/home#index', as: :authenticated_root
  end

  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/goal.rb
class Goal < ApplicationRecord
  belongs_to :category
  has_many :ledgers
  enum frequency: {
      daily: 0,
      weekly: 1,
      monthly: 3,
      other: 4
  }

  validates :name, presence: true
  validates :frequency, presence: true

  def progress
    return nil if goal_value.nil?

    case frequency.to_sym
    when :daily
      total = daily_ledger_value
    when :weekly
      total = weekly_ledger_value
    when :monthly
      total = monthly_ledger_value
    when :other
      total = target_date_ledger_value
    end

    total
  end

  def progress_percentage
    (Float(progress) / goal_value) * 100
  end

  def progress_unit
    case frequency.to_sym
    when :daily
      'today'
    when :weekly
      'this week'
    when :monthly
      'this month'
    when :other
      "till #{end_target}"
    end
  end

  private

  def daily_ledger_value
    # We don't care about new_entry_add_to_total for a daily goal
    # We sum all entered values for a day
    ledgers.where(created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day).sum('value')
  rescue
    nil
  end

  def weekly_ledger_value
    if new_entry_add_to_total? || category.unit_type == 'boolean'
      ledgers
          .where(created_at: Time.zone.now.beginning_of_week..Time.zone.now.end_of_day)
          .sum('value')
    else
      ledgers
          .where(created_at: Time.zone.now.beginning_of_week..Time.zone.now.end_of_day)
          .order('created_at DESC').limit(1)[0]['value']
    end
  rescue
    nil
  end

  def monthly_ledger_value
    if new_entry_add_to_total? || category.unit_type == 'boolean'
      ledgers
          .where(created_at: Time.zone.now.beginning_of_month..Time.zone.now.end_of_day)
          .sum('value')
    else
      ledgers
          .where(created_at: Time.zone.now.beginning_of_month..Time.zone.now.end_of_day)
          .limit(1)[0]['value']
    end
  rescue
    nil
  end

  def target_date_ledger_value
    if new_entry_add_to_total?
      ledgers.sum('value')
    else
      ledgers.order('created_at DESC').limit(1)[0]['value']
    end
  end
end

app/controllers/admin/goals_controller.rb
module Admin
  class GoalsController < Admin::ApplicationController
    before_action :authenticate_user!

    def new
      @goal = Goal.new
      @categories = current_user.categories
    end

    def create
      @goal = Goal.new(goal_params)
      if @goal.save
        flash[:notice] = 'Goal created successfully'
        redirect_to admin_goals_path
      else
        flash[:alert] = 'Invalid goal'
        render 'new'
      end
    end

    def index
      @goals = current_user.goals
    end

    def show
      @goal = find_or_redirect(:goal, params[:id])
    end

    def edit
      @goal = find_or_redirect(:goal, params[:id])
      @categories = current_user.categories
    end

    def update
      @goal = find_or_redirect(:goal, params[:id])
      return if @goal.nil?
      if @goal.update(goal_params)
        flash[:notice] = 'Goal updated'
        redirect_to admin_goals_path
      else
        flash[:alert] = 'Could not update the goal'
        redirect_to edit_admin_goal_path(params[:id])
      end
    end

    def destroy
      @goal = find_or_redirect(:goal, params[:id])
      @goal.delete

      flash[:notice] = "Goal #{@goal.name} was successfully deleted"
      redirect_to admin_goals_path
    end

    private

    def goal_params
      params.require(:goal).permit(:name,
                                   :category_id,
                                   :end_target,
                                   :frequency,
                                   :goal_value,
                                   :new_entry_add_to_total)
    end
  end
end

app/views/admin/goals/_form.html.erb
<div class="card-body">
  <%= form_for [:admin, goal], html: {class: 'form-horizontal'} do |f| %>
    <% if goal.errors.any? %>
      <% goal.errors.full_messages.each do |msg| %>
        <div class="alert alert-danger"><%= msg %></div>
      <% end %>
    <% end %>

    <div class="form-group row">
      <%= f.label :name, class: 'col-sm-2 form-control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :name, class: 'form-control', placeholder: 'read Ready Player One' %>
      </div>
    </div>
    <div class="line"></div>
    <div class="form-group row">
      <%= f.label :category, class: 'col-sm-2 form-control-label' %>
      <div class="col-sm-10">
        <%=
          f.select(
              :category_id,
              options_for_select(
                  categories.all.map do |c|
                    [c.name, c.id, { parent_type: c.unit_type, unit_name: c.unit_name }]
                  end,
                  selected: goal[:category_id]
              ),
              {},
              {
                  class: 'form-control',
                  onChange: 'show_category_unit_name();'
              }
          )
        %>
      </div>
    </div>

    <div class="form-group row">
      <%= f.label :target, class: 'col-sm-2 form-control-label' %>
      <div class="col-sm-2">
        <%= f.radio_button :frequency, 'daily', onclick: "disable_end_target()" %>
        <%= f.label "frequency_daily", 'Daily' %>
      </div>

      <div class="col-sm-2">
        <%= f.radio_button :frequency, 'weekly', onclick: "disable_end_target()" %>
        <%= f.label "frequency_weekly", 'Weekly' %>
      </div>

      <div class="col-sm-2">
        <%= f.radio_button :frequency, 'monthly', onclick: "disable_end_target()" %>
        <%= f.label "frequency_monthly", 'Monthly' %>
      </div>

      <div class="col-sm-4" style="display:flex; flex-direction:row">
        <%= f.radio_button :frequency, 'other', onclick: "enable_end_target()" %>
        &nbsp;
        <%= f.label "frequency_other", 'Other' %>
        &nbsp;&nbsp;
        <%= f.text_field :end_target, class: 'datepicker', style: 'flex: 1', id: 'end_target_id' %>
      </div>
    </div>
    <div class="form-group row" id="goal_value_div">
      <%= f.label :goal_value, class: 'col-sm-2 form-control-label' %>
      <div class="col-sm-8">
        <%= f.text_field :goal_value, class: 'form-control', placeholder: '500' %>
      </div>
      <div id="unit_name"></div>
    </div>
    <div class="form-group row">

      <%= f.label :new_entry_add_to_total, 'Add new entries to total', class: 'col-sm-2 form-control-label' %>
      <div class="col-sm-10">
        <%= f.check_box :new_entry_add_to_total, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group row">
      <div class="col-sm-2">&nbsp;</div>
      <div class="col-sm-4">
        <%= f.submit "Submit", class: 'btn btn-primary' %>
        <%= link_to 'Cancel', admin_goals_path, class: 'btn btn-secondary' %>
      </div>
    </div>
  <% end %>
</div>
<script>
  <% if goal.new_record? || goal.frequency != 'other' %>
  document.getElementById('end_target_id').disabled = true;
  <% end %>

  $(function () {
    $('.datepicker').datepicker({dateFormat: "yy-mm-dd"}).val();
  });

  function disable_end_target() {
    document.getElementById('end_target_id').value = '';
    document.getElementById('end_target_id').disabled = true;
  }

  function enable_end_target() {
    document.getElementById('end_target_id').disabled = false;
  }

  function show_category_unit_name() {
    document.getElementById('unit_name').innerText = '';

    var category = document.getElementById("goal_category_id");
    var unit_name = category.options[category.selectedIndex].getAttribute('unit_name');
    var category_type = category.options[category.selectedIndex].getAttribute('parent_type');
    if(unit_name != '') {
      document.getElementById('unit_name').innerText = unit_name
    }else if (category_type == 'boolean' ) {
      document.getElementById('unit_name').innerText = 'times'
    }
  }

  show_category_unit_name()

</script>

app/views/admin/goals/delete.html.erb
<h1>Admin::Goals#delete</h1>
<p>Find me in app/views/admin/goals/delete.html.erb</p>

app/views/admin/goals/edit.html.erb
<div class="card-header d-flex align-items-center">
  <h3 class="h4">Edit Goal</h3>
</div>
<%= render 'form', goal: @goal, categories: @categories %>

app/views/admin/goals/index.html.erb
<%= stylesheet_link_tag 'admin/goals', media: 'all', 'data-turbolinks-track': 'reload' %>
<div class="card">
  <div class="card-header d-flex align-items-center">
    <h3 class="h4">Goals</h3>
  </div>
  <div class="container-fluid">
    <% @goals.each_slice(3) do |goal_batch| %>
      <div class="row" style="padding: 5px">
        <% goal_batch.each do |goal| %>
          <div class="col-md-4 border rounded">
            <div class="row icons">
              <div class="col-md-1">
                <%= link_to(new_admin_ledger_path(goal: goal), id: "log_goal_#{goal.id}") do %>
                  <%= fa_icon 'save', class: 'icons' %>
                <% end %>
              </div>
              <div class="col-md-8"></div>
              <div class="col-md-1">
                <%= fa_icon 'info', class: 'icons' %>
              </div>
              <div class="col-md-1">
                <%= link_to(edit_admin_goal_path(goal), id: "edit_goal_#{goal.id}") do %>
                  <%= fa_icon 'edit', class: 'icons' %>

                <% end %>
              </div>
              <div class="col-md-1">
                <%= link_to(
                        admin_goal_path(goal),
                        method: :delete,
                        data: {confirm: 'Are you sure?'},
                        authenticity_token: true,
                        id: "delete_goal_#{goal.id}") do %>
                  <%= fa_icon 'trash', class: 'danger' %>

                <% end %>
              </div>
            </div>

            <div class="row">
              <div class="col-md-12 text-center">
                <%= link_to(goal.name, admin_goal_url(goal), class: 'goal-title') %>
              </div>
            </div>
            <% unless goal.progress.nil? %>
              <div class="row" style="padding-top: 10px;">
                <div class="col-md-2"></div>

                <div class="col-md-8">
                  <div class="progress">
                    <div class="progress-bar" role="progressbar" style="width: <%= goal.progress_percentage %>%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                  </div>

                  <div class="text-center" style="padding-top: 5px">
                    <%= goal.progress %>/<%= goal.goal_value %>
                  </div>
                  <div class="text-center">
                    <%= goal.progress_unit %>
                  </div>
                </div>

                <div class="col-md-2"></div>
              </div>

            <% end %>

          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>
<%= link_to 'Add', new_admin_goal_path, class: 'btn btn-primary' %>

app/views/admin/goals/new.html.erb
<div class="card-header d-flex align-items-center">
  <h3 class="h4">Add Goal</h3>
</div>
<%= render 'form', goal: @goal, categories: @categories %>

app/views/admin/goals/show.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center">
    <h3 class="h4"><%= @goal.name %></h3>
  </div>
  <% unless @goal.progress.nil? %>

    <div class="card-body">
      <div class="card-header d-flex align-items-center">
        <h3 class="h4">Progress</h3>
        <span>
          (<%= @goal.progress %> out of <%= @goal.goal_value %> <%= @goal.progress_unit %>)
        </span>
      </div>
      <div class="progress">
        <div class="progress-bar" role="progressbar" style="width: <%= @goal.progress_percentage %>%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
      </div>
    </div>

  <% end %>
  <div class="card-body">
    <%= month_calendar events: @goal.ledgers do |date, ledgers| %>
      <%= date %>
      <% ledgers.each do |ledger| %>
        <div>
          <%= fa_icon 'check 2x', class: 'success' %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="card-body">
    <% if @goal.category.unit_type == 'boolean' %>
      <%= column_chart admin_charts_goal_logs_path('daily_logged_yes_no', @goal.id, params[:start_date]) %>
    <% else %>
      <%= line_chart admin_charts_goal_logs_path('raising', @goal.id) %>
    <% end %>
  </div>
</div>

app/views/admin/goals/update.html.erb
<h1>Admin::Goals#update</h1>
<p>Find me in app/views/admin/goals/update.html.erb</p>